#!/usr/bin/env python3
"""Merge banned terms from vendor trees + house seed into references/banned-words.md."""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "references" / "banned-words.md"
HOUSE = ROOT / "references" / "house-overrides.md"

# Paths relative to vendor roots that often hold lists
SCAN_GLOBS = (
    "**/banned*.md",
    "**/ANTI-SLOP.md",
    "**/SKILL.md",
    "**/references/*.md",
)

WORD_LINE = re.compile(
    r"^\s*[-*]?\s*\**([a-zA-Z][a-zA-Z0-9' -]{1,40})\**\s*(?:#.*)?$",
    re.M,
)


def harvest_file(path: Path, source: str, bucket: dict[str, set[str]]) -> None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return
    # crude: pull backtick or bold tokens and list items that look like ban entries
    for m in re.finditer(
        r"`([a-z][a-z0-9' -]{2,40})`|\*\*([a-z][a-z0-9' -]{2,40})\*\*|"
        r"(?:delve|tapestry|landscape|pivotal|vibrant|testament|beacon|foster|"
        r"resonate|underscore|utilize|leverage|seamless|robust|holistic|"
        r"cutting-edge|game-changer|multifaceted|realm|interplay|empower|harness)",
        text,
        re.I,
    ):
        term = (m.group(1) or m.group(2) or m.group(0)).lower().strip()
        if len(term) < 3:
            continue
        bucket[term].add(source)


def main() -> None:
    bucket: dict[str, set[str]] = defaultdict(set)

    # seed house terms from existing banned-words if present
    if OUT.exists():
        for line in OUT.read_text(encoding="utf-8").splitlines():
            if "  # sources:" in line:
                term, _, rest = line.partition("  # sources:")
                term = term.strip().lower()
                if term:
                    for s in rest.split(","):
                        bucket[term].add(s.strip())

    vendor = ROOT / "vendor"
    if vendor.is_dir():
        for child in sorted(vendor.iterdir()):
            if not child.is_dir():
                continue
            source = child.name.split("-")[0] if "-" in child.name else child.name
            for pat in SCAN_GLOBS:
                for f in child.glob(pat):
                    if f.is_file():
                        harvest_file(f, source, bucket)

    # always ensure core house set
    for t in (
        "delve",
        "tapestry",
        "pivotal",
        "vibrant",
        "testament",
        "utilize",
        "seamless",
        "game-changer",
        "multifaceted",
    ):
        bucket[t].add("house")

    lines = [
        "# Banned / high-suspicion vocabulary (composite)",
        "",
        f"**Regenerated by** `scripts/merge-lexicon.py`.",
        "Format: `term  # sources: a, b`",
        "",
        "## Words",
        "",
        "```",
    ]
    for term in sorted(bucket.keys()):
        src = ", ".join(sorted(bucket[term]))
        lines.append(f"{term}  # sources: {src}")
    lines.extend(
        [
            "```",
            "",
            "## See also",
            "",
            "- `house-overrides.md` — technical/IC exceptions",
            "- `UPSTREAM.md` — vendor policy",
            "",
        ]
    )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(bucket)} terms)")


if __name__ == "__main__":
    main()
